// expand-content.mjs — generate 60 more meditations, 40+ prayers, 12 praise songs
// Writes JSON to content/meditations/, content/prayers/, content/praise/
// Run with: node scripts/expand-content.mjs

import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const MEDITATIONS_DIR = path.join(ROOT, 'content/meditations');
const PRAYERS_DIR = path.join(ROOT, 'content/prayers');
const PRAISE_DIR = path.join(ROOT, 'content/praise');

await mkdir(MEDITATIONS_DIR, { recursive: true });
await mkdir(PRAYERS_DIR, { recursive: true });
await mkdir(PRAISE_DIR, { recursive: true });

// ─── helpers ───────────────────────────────────────────────────
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function writeJson(dir, name, obj) {
  const p = path.join(dir, name);
  await writeFile(p, JSON.stringify(obj, null, 2) + '\n');
  return p;
}

// ─── 60 new meditations (days 31-90) ───────────────────────────
// Themes: grief, joy, faith-struggle, parenting, work, marriage, illness,
// hope, forgiveness, gratitude, rest, courage, wisdom, focus
const meditations = [
  // ── Grief & loss ──
  { theme:'grief', title:'In the Valley of the Shadow', ref:'Psalm 23:4', text:'Even though I walk through the darkest valley, I fear no evil; for you are with me; your rod and your staff— they comfort me.', reflection:'Death is not the last word. The shadow has a length but not a depth. Walk slowly. There is no rush to be on the other side of grief.', body:`Find a place where no one can see you. Let the tears come if they want to come. They have been waiting.\n\nYou do not have to pray the right words. You do not have to be strong. You do not have to make sense of this. The Lord is your shepherd; even here, in the valley, He is here.\n\nRead the psalm slowly. The words are old. They have been said over a billion grieving mouths before yours. They are still true. They will be true tomorrow.\n\nYour good shepherd is not ahead of you, beckoning. He is beside you, walking. Or behind you, guarding. Sometimes you cannot see Him. That does not mean He is not there.\n\nWhen you are ready, set one foot in front of the other. There is no hurry. The valley is not infinite, even when it feels infinite.`, prayer:'Lord, walk with me through this. I cannot see the path. Be my feet when mine will not move. Amen.', dur:300, season:'ordinary' },
  { theme:'grief', title:'A Year of Firsts', ref:'Ecclesiastes 3:4', text:'A time to weep, and a time to laugh; a time to mourn, and a time to dance.', reflection:'The firsts are the hardest. The first morning, the first birthday, the first holiday without them. Each one is a small dying and a small living.', body:`Light a candle. Or do not. Both are fine.\n\nThe first year after loss is full of landmines. Ordinary moments ambush you. A song on the radio. A smell from a kitchen. The way someone laughs in a checkout line.\n\nYou will think you are doing well, and then something will break you open. This is not failure. This is the heart updating its map of the world.\n\nDo not rush the year. Do not pretend you are past it. The Lord, who numbers the very hairs of your head, is numbering these days with you. They are precious in His sight, even when they feel unbearable.\n\nWhen the laughter returns, let it. When the dance returns, let it. Grief is not a betrayal of love. It is the price of it.`, prayer:'Lord, this year has been long. Be patient with me. Let me love well, even now. Amen.', dur:300, season:'ordinary' },
  { theme:'grief', title:'For a Child Lost', ref:'Matthew 18:10', text:'See that you do not despise one of these little ones; for I tell you, their angels in heaven always behold the face of my Father.', reflection:'No parent should bury a child. The order of things is wrong, and no theology fully makes it right. But God is with you in the wrongness.', body:`I do not have good words. I do not have a verse to make this okay. There is no okay.\n\nThere is only this: the Lord of hosts is near to the brokenhearted. He does not fix it. He does not explain it. He weeps with you, because His heart breaks at the same things yours does.\n\nYou will wake up tomorrow. That, in itself, will be a kind of grace. You will breathe. You will put one foot in front of the other. Not because you are brave, but because He carries you when you cannot carry yourself.\n\nYour child is not lost. They are held. By hands bigger than yours.`, prayer:'Lord, hold my child. And hold me. We are both lost without each other. Be our meeting place. Amen.', dur:300, season:'ordinary' },
  { theme:'grief', title:'The Empty Chair', ref:'Revelation 21:4', text:'He will wipe every tear from their eyes. Death will be no more; mourning and crying and pain will be no more.', reflection:'The chair is still there. So is the absence. Heaven does not erase; it transforms. One day, you will see them again, and the years between will feel like a long breath held.', body:`Set a place for them. Or do not. Both are fine. Some days the empty chair is unbearable. Some days it is a kind of company.\n\nThe promise is not that you will stop missing them. The promise is that one day, missing will be no more, because the one you miss will be standing right in front of you, and you will not be able to believe you ever lived a day without them.\n\nThat day is real. It is closer than it feels. Hold on for it.`, prayer:'Lord, I miss them. Today, I miss them so much. Hold the space open. I am coming. Amen.', dur:280, season:'ordinary' },

  // ── Faith struggle & doubt ──
  { theme:'courage', title:'When You Are Not Sure God Is There', ref:'Psalm 42:3', text:'My tears have been my food day and night, while people say to me continually, "Where is your God?"', reflection:'Doubt is not the opposite of faith. Indifference is. As long as you are asking the question, you are still in the conversation.', body:`It is okay to not be sure. The Bible is full of people who were not sure. David cried out, "How long, O Lord?" Job demanded an audience. Thomas needed to see the wounds. They made it into the story, and so will you.\n\nDoubt is often faith's honest form. It is what faith looks like when it stops pretending.\n\nYou do not have to perform certainty. You do not have to defend God. He can handle your questions. He has been handling them since Abraham, since Moses, since the Israelites in the desert who wondered, every forty years, why they were following this cloud.\n\nBe honest. Be faithful to the honesty. The rest will follow.`, prayer:'Lord, I believe; help my unbelief. That is all I have right now. It is enough. Amen.', dur:300, season:'ordinary' },
  { theme:'courage', title:'When Prayer Feels Like Talking to the Ceiling', ref:'Romans 8:26', text:'The Spirit himself intercedes for us with sighs too deep for words.', reflection:'Even when you cannot pray, the Spirit prays for you. Your silence is not emptiness; it is a space the Spirit fills.', body:`You sat down to pray. The words did not come. They rarely do, on the days you most need them.\n\nThat is okay. Sit there anyway. Let the silence be the prayer. God is not waiting for the right phrases. He is with you in the quiet.\n\nSometimes prayer is a long, slow exhale. Sometimes it is a walk in the woods. Sometimes it is sitting on a kitchen floor at 3am, holding a coffee mug that has gone cold.\n\nAll of it is prayer. None of it is wasted. The Spirit is doing the work your words cannot do.`, prayer:'Lord, I have no words. You do not need them. Sit with me. Amen.', dur:240, season:'ordinary' },
  { theme:'courage', title:'For the One Questioning Everything', ref:'Habakkuk 2:3', text:'For the vision is yet for the appointed time; it speaks of the end, and does not lie. Though it tarries, wait for it; for it will surely come.', reflection:'Faith is not a feeling. It is a direction. You can walk in a direction without feeling it.', body:`You have read the arguments. You have read the counter-arguments. You have weighed the evidence, and you are not sure.\n\nThat is not a failure of intelligence. It is the normal shape of a sincere search. Almost no one comes to faith by reading the right book at the right time. Most of us come to faith the long way, by living, by hurting, by being loved by someone who showed us what it looks like.\n\nKeep walking. Keep asking. Keep showing up to the questions, even when they are uncomfortable. The fact that you are reading a meditation like this is itself a kind of evidence.\n\nGod is patient. He has time.`, prayer:'Lord, I am not sure. I want to be. Walk with me until I am. Amen.', dur:300, season:'ordinary' },
  { theme:'courage', title:'When You Feel Far From God', ref:'Jeremiah 29:13', text:'You will seek me and find me, when you seek me with all your heart.', reflection:'The feeling of distance is often a sign of growth. The closer you get to the sun, the hotter it feels.', body:`The feeling of distance is not the same as distance. The sun does not move. You do.\n\nSome seasons feel far from God because you are. Some seasons feel far from God because you are closer than you have ever been, and the heat is unfamiliar.\n\nBoth are normal. Both are temporary. The shepherd seeks the lost sheep, not the other way around. If you are moving at all, even one step, even in the wrong direction, you are still moving within His pasture.\n\nHe is not angry. He is not far. He is closer than the thought you are thinking right now.`, prayer:'Lord, I feel far. Pull me close. Or just let me feel You. Either is enough. Amen.', dur:240, season:'ordinary' },

  // ── Joy & gratitude ──
  { theme:'gratitude', title:'For the Small, Free Good', ref:'1 Thessalonians 5:18', text:'Give thanks in all circumstances; for this is God\'s will for you in Christ Jesus.', reflection:'Joy is not a feeling. It is a practice. The feeling comes and goes. The practice is what holds you when the feeling leaves.', body:`The light this morning. The cool water. The friend who texted first. The fact that the dog is still alive. The stranger who held the door. The song that came on at exactly the right second.\n\nNone of these are big. None of these are news. All of them are grace.\n\nTake thirty seconds. Name three of them. The naming is the practice. The naming is what turns a day from passing to received.\n\nYou do not have to feel grateful to be grateful. The feeling will catch up. The feet come first.`, prayer:'Lord, thank You for the small good things. Especially the small good things. They are the big ones in disguise. Amen.', dur:240, season:'ordinary' },
  { theme:'joy', title:'For Pure, Uncomplicated Joy', ref:'Psalm 16:11', text:'In your presence there is fullness of joy; at your right hand are pleasures forevermore.', reflection:'Joy is not the absence of sorrow. It is the presence of something larger than sorrow. The Lord is that larger thing.', body:`Something made you smile today. You did not earn it. You did not plan it. It just arrived, like sunlight through a window.\n\nThis is what the Bible means by joy. Not the emotion you can manufacture. The emotion that arrives unbidden, because something or someone has touched the real you, the one beneath the worry and the schedule and the small, hard things.\n\nGod is the source of that. He is in the smile. He is in the sunlight. He is the sunlight.\n\nReceive it. Do not rush past it. Do not turn it into a project. Just stand in it. Just let it be.`, prayer:'Lord, thank You for joy. The unexpected, unearned kind. The kind that finds me. Amen.', dur:240, season:'ordinary' },
  { theme:'gratitude', title:'For the Body That Carried You Here', ref:'1 Corinthians 6:19', text:'Do you not know that your body is a temple of the Holy Spirit within you?', reflection:'You are a miracle walking. A thinking, breathing, feeling miracle, and you treat yourself like a machine.', body:`Your body has done a lot for you today. It breathed without you asking. It pumped blood. It walked you here. It digested breakfast. It blinked.\n\nIt has also been tired, sore, hungry, anxious, and uncomfortable, and it has still shown up, every day, for the years you have been alive.\n\nThank it. Not in a self-help way. In a prayer way. The body is not a problem to fix. It is a gift to steward. A temple, the psalmist says. A place where the Holy Spirit has chosen to live.\n\nStretch. Drink water. Go to bed at a reasonable hour. These are not small things. They are forms of worship.`, prayer:'Lord, thank You for this body. Help me care for it the way You care for it. Amen.', dur:240, season:'ordinary' },

  // ── Work & calling ──
  { theme:'focus', title:'For the Work That Feels Pointless', ref:'Colossians 3:23', text:'Whatever you do, work heartily, as for the Lord and not for men.', reflection:'You are not the final judge of what is meaningful. The work is not measured by its outcome but by the love you bring to it.', body:`The meeting that should have been an email. The deck you spent three days on that no one will read. The hour you spent on hold. The email you answered ten times.\n\nNone of this feels like a vocation. Most work does not, most of the time. That is normal. It does not mean the work is not sacred.\n\nEvery honest job, even the boring parts, is a way of saying: I will be faithful. I will show up. I will do the small things well. The Lord does not require your work to be famous. He requires it to be done.\n\nDo the next small thing. Then the next one. The meaning comes later, or it does not, and the meaning is not the point.`, prayer:'Lord, give me patience with this work. Help me to do it as unto You, even when I cannot see You. Amen.', dur:240, season:'ordinary' },
  { theme:'focus', title:'For the Boss You Cannot Stand', ref:'1 Peter 2:18', text:'Servants, be subject to your masters with all respect, not only to the good and gentle but also to the unjust.', reflection:'You do not have to love your boss to learn from this season. Some lessons are not about the boss.', body:`The Sunday evening dread. The Sunday evening weight. The voice in your head running the conversation you are afraid you will have on Monday.\n\nThis is hard. Some seasons are just hard. You do not have to pretend they are not.\n\nThe Lord is not asking you to enjoy this. He is asking you to stay soft in the middle of it. To not become the thing that is being done to you. To keep your conscience, your kindness, your sleep.\n\nIf it is wrong, change what you can. If you cannot change it, find the people who see you, and let them hold the parts of you this job is threatening to take.\n\nThis too is a season. Seasons end.`, prayer:'Lord, be my strength at work. Help me not to become hard. And show me the door when it is time to walk through it. Amen.', dur:300, season:'ordinary' },
  { theme:'wisdom', title:'For a Hard Decision', ref:'James 1:5', text:'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.', reflection:'Most decisions are not between right and wrong. They are between two goods, or two harms. Be gentle with yourself.', body:`You have done the work. You have weighed the options. You have asked the people you trust. The answer is still not clear.\n\nThat is okay. Most real decisions are made in the fog, not the clarity. Faith is not the absence of fog. Faith is one more step in it.\n\nAsk the Lord. Not for a sign. For wisdom. He gives it generously, James says, without scolding. He will give it to you. Probably not as a flash of lightning. Probably as a slow settling, a quiet rightness, a few weeks later when you look back and see.\n\nDecide. Live into the decision. The Lord will meet you there.`, prayer:'Lord, I cannot see the path. Give me wisdom. Give me courage. Give me peace with whichever door I walk through. Amen.', dur:300, season:'ordinary' },
  { theme:'wisdom', title:'For a Door Closing', ref:'Revelation 3:7', text:'These are the words of him who is holy and true, who holds the key of David. What he opens no one can shut, and what he shuts no one can open.', reflection:'A closed door is not always a punishment. Sometimes it is protection. Sometimes it is redirection.', body:`They said no. The offer did not come. The person you loved chose someone else. The thing you worked for went to someone else. The door you had been pushing against for years quietly, finally, definitely closed.\n\nThis is one of the hardest kinds of loss, because it is not a death. It is a non-birth. A future that was alive in your mind, and is now not.\n\nGrieve it. Do not skip this. The grief is real, even though nothing happened that you can point to.\n\nThen, slowly, look around. The Lord is not behind you, pointing at the closed door. He is ahead of you, opening another. You cannot see it yet. Trust that it is there.`, prayer:'Lord, this door has closed. I do not understand. Walk with me toward the next one. Amen.', dur:300, season:'ordinary' },
  { theme:'wisdom', title:'For a Door Opening', ref:'Isaiah 43:19', text:'Behold, I am doing a new thing; can you not perceive it? I will make a way in the wilderness and rivers in the wasteland.', reflection:'A new thing is rarely comfortable. The new thing asks you to leave the old thing, and the old thing is at least familiar.', body:`The call came. The offer came. The opportunity you had stopped praying for showed up in your inbox. You are excited. You are terrified. Both are correct.\n\nThe Lord is doing a new thing. He has been doing new things since the beginning of time. Each one required someone to step out of a boat, leave a country, walk into a furnace, give up a meal ticket, follow a stranger.\n\nYou are the next one in the line. Step. The fear is not a sign you are doing it wrong. The fear is a sign you are doing it right.\n\nThe Lord, who called you to it, will be faithful in it.`, prayer:'Lord, I am stepping. Hold my hand. Hold my heart. And do not let me look back. Amen.', dur:300, season:'ordinary' },

  // ── Marriage & relationships ──
  { theme:'love', title:'For the Marriage That Has Lost Its Spark', ref:'1 Corinthians 13:7', text:'Love bears all things, believes all things, hopes all things, endures all things.', reflection:'The spark is not the marriage. The marriage is what you build by choosing to show up, especially when the spark has wandered off.', body:`You can live with someone for ten, twenty, thirty years and forget, in the middle of an ordinary Tuesday, why you chose them. This is not a crisis. It is a feature of long love.\n\nThe early spark was never going to last. It could not. It was a spark, not a fire. The fire is what you are building now, slowly, by getting through the Tuesday.\n\nTell them one specific thing you appreciate about them. Tonight. Not "I love you" — too easy. Something specific. "I noticed you took out the trash without being asked." "Thank you for the way you handled that with the kids."\n\nThe marriage does not need a spark. It needs a thousand small attentions. The spark comes back on its own, when you stop looking for it.`, prayer:'Lord, help me love this person well today. Not dramatically. Just well. Amen.', dur:300, season:'ordinary' },
  { theme:'love', title:'For the Friend You Have Neglected', ref:'Proverbs 27:9', text:'Perfume and incense make the heart glad; the sweetness of a friend is better than one\'s own counsel.', reflection:'Friendship is a living thing. It dies from neglect faster than from anything else. Send the text.', body:`You have been meaning to call them. For weeks. For months. The message has been drafted in your head a dozen times.\n\nThe friendship is not dead. But it is sleeping, and the longer it sleeps, the harder it is to wake.\n\nSend the text. Not a long one. "Thinking of you. Hope you are well." That is enough. That is the whole assignment.\n\nFriendship is a thousand small acts of remembering. The remembering is the love. The remembering is what makes the friend a friend.`, prayer:'Lord, thank You for friends. Help me to be a better one. Show me one I should reach out to today. Amen.', dur:240, season:'ordinary' },
  { theme:'forgiveness', title:'For the One Who Hurt You', ref:'Matthew 18:22', text:'Jesus said to him, "I do not say to you seven times, but seventy times seven."', reflection:'Forgiveness is not a feeling. It is a practice. It is choosing, again and again, to not let this person rent space in your head.', body:`You have every right to be angry. The thing that was done to you was wrong. The anger is not a sin. It is a signal that something precious was violated.\n\nBut the anger is also eating you. You have noticed that. The hurt has become a hobby. The resentment a routine. The person who hurt you is in your head more than they ever were when they were actually in your life.\n\nForgiveness is not saying it was okay. Forgiveness is saying: I am no longer going to carry this for you. It is heavy. It is yours. Take it back.\n\nYou do not have to feel it to do it. The feeling will come later, or it will not. The decision is what matters.`, prayer:'Lord, I am not ready to forgive. But I am ready to want to forgive. Start there. Amen.', dur:300, season:'ordinary' },
  { theme:'forgiveness', title:'For the Parent Who Got It Wrong', ref:'Exodus 20:12', text:'Honor your father and your mother, that your days may be long in the land.', reflection:'They were not perfect. They were not even always good. But they were yours, and you came from them, and the long work of love is what the Lord asks.', body:`You did not get what you needed. They were too busy, or too wounded, or too young, or too hard. You learned to perform. You learned to be the easy child. You learned to not need.\n\nThat was not okay. And they were, probably, doing the best they could with what they had been given.\n\nYou do not have to be at peace with it yet. You do not have to make them into a saint. You only have to do the long, slow work of letting them be human, and letting yourself be free of the role you took on to survive them.\n\nHonor them. Not because they earned it. Because the work of honoring is what frees you.`, prayer:'Lord, help me to honor them, and to not let what was done to me be done to anyone else. Amen.', dur:300, season:'ordinary' },
  { theme:'love', title:'For the Child Who Is Hard to Love', ref:'1 Corinthians 13:4', text:'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.', reflection:'Patience is not waiting for the child to become who you wanted. It is showing up to who they actually are.', body:`You love them. You do. But some days the love is buried under the noise, the defiance, the same question asked forty times, the kicking, the screaming, the lying, the sweetness that is gone.\n\nYou do not love them less. You are just tired. And tired parents do not need more advice. They need a quiet room and a God who sees them.\n\nThe Lord sees you. He sees the work you are doing, the patience that is being asked of you, the small ways you are showing up that no one will ever thank you for. He is pleased with you. Not with the house, not with the dinner, not with the bedtime. With you.\n\nYou can do this. Not because you are strong. Because He is.`, prayer:'Lord, give me patience. Help me see my child the way You see them. And please give me a little quiet. Amen.', dur:300, season:'ordinary' },

  // ── Health & body ──
  { theme:'courage', title:'For a Hard Diagnosis', ref:'Psalm 139:16', text:'Your eyes saw my unformed substance; in your book were written, every one of them, the days that were formed for me, when as yet there was none of them.', reflection:'Your body is not a thing that betrayed you. It is a body that is going through something. There is a difference.', body:`The word the doctor used is going to live in your head for a while. Maybe forever. It is a strange word, a medical word, and it does not have the feel of a word that belongs to your life. But it does, now.\n\nYou are allowed to be afraid. You are allowed to be angry. You are allowed to sit on the bathroom floor and not be okay.\n\nThe Lord is not the author of the disease. He is the one sitting beside you in the waiting room. He is the one who, in some way past understanding, has numbered your days, and is in all of them. None of them are wasted. None of them are outside His care.\n\nYou are not alone. You are not your diagnosis. You are still you, beloved, seen, and held.`, prayer:'Lord, walk with me through this. I do not understand it. I do not have to. Be my strength. Amen.', dur:300, season:'ordinary' },
  { theme:'courage', title:'For a Surgery Tomorrow', ref:'Isaiah 41:10', text:'Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.', reflection:'You have done the work of showing up. The rest is in hands bigger than yours.', body:`Tomorrow morning you will wake up early, before the rest of the world, and you will drive to a building where people in scrubs will take care of you.\n\nTonight, set out your clothes. Set out your phone charger. Tell someone you love them. Eat what they told you to eat, do not eat what they told you not to eat. Do the small things. The small things are how you keep your hands in your own life.\n\nThe Lord will be in the operating room. Not as a surgeon. As the one who holds the surgeon\'s hands, who steadies, who keeps.\n\nYou will wake up. The worst part will be the wait. The wait is almost over.`, prayer:'Lord, hold the surgeon\'s hands. Be with the nurses. Watch over me. And let me wake up grateful. Amen.', dur:240, season:'ordinary' },
  { theme:'courage', title:'For a Body in Pain', ref:'2 Corinthians 12:9', text:'My grace is sufficient for you, for my power is made perfect in weakness.', reflection:'Pain is not a punishment. It is a messenger. Sometimes the only way to hear the body is for the body to scream.', body:`Today is a bad day. The pain is loud, and the small things you used to do without thinking are now mountains. You are not weak. Pain is hard. Pain that other people cannot see is harder.\n\nThe Lord is not asking you to be grateful for the pain. He is asking you to not be alone in it. He is in the bed with you, in the same way He was in the furnace with Shadrach, Meshach, and Abednego. The fire did not go away. He was in it with them.\n\nTake the medicine if you have it. Do not be a hero. Call the doctor if you need to. Rest. Rest is not laziness. Rest is a holy thing.\n\nThis day will end. Tomorrow may be a little better. You are not alone.`, prayer:'Lord, I hurt. Hold me. Be the warmth when I cannot find it. Amen.', dur:240, season:'ordinary' },
  { theme:'rest', title:'For the Caregiver', ref:'Galatians 6:9', text:'Let us not grow weary of doing good, for in due season we will reap, if we do not give up.', reflection:'You cannot pour from an empty cup. Rest is not abandoning them. Rest is what makes you able to stay.', body:`You are tired in a way that sleep does not fix. The kind of tired that lives in the bones. The kind of tired that comes from loving someone through a long, hard season.\n\nYou are not failing. You are doing the hardest, holiest work there is. But the holy work will hollow you out if you do not let yourself be filled again.\n\nTake a break today. Not a long one. An hour. A walk. A coffee with a friend. A bath. A book. Something that is just for you, not for them.\n\nThe Lord, who watched over Israel in the wilderness, is watching over you. He sees the late nights. He sees the sacrifice. He is pleased. And He is saying, rest.`, prayer:'Lord, I am tired. Be my rest. And show me one small way to be kind to myself today. Amen.', dur:300, season:'ordinary' },

  // ── Spiritual disciplines & seasons ──
  { theme:'stillness', title:'For a Holy Lent', ref:'Joel 2:12', text:'Even now, declares the Lord, return to me with all your heart, with fasting, with weeping, and with mourning.', reflection:'Lent is not a diet. Lent is a clearing. It is the long, slow work of making space for the only thing that satisfies.', body:`For these forty days, something is going to be set down. It does not have to be impressive. Coffee. Sugar. Social media. The morning news. A habit of complaint.\n\nThe point is not the thing. The point is the space the thing leaves behind. That space is for God.\n\nYou will fail. You will have the coffee on day three. You will be irritated with your kids by day twelve. You will be tempted to give up the whole thing by day twenty.\n\nKeep going. Lent is not a performance. It is a practice. The failure is part of the practice. The returning, again and again, is the point.\n\nThe Lord is waiting. He has time. He has patience. He is not grading you.`, prayer:'Lord, give me strength to set this down, and the grace to pick it up when I fail, and the wisdom to keep returning. Amen.', dur:300, season:'lent' },
  { theme:'joy', title:'For Easter Morning', ref:'1 Corinthians 15:54', text:'Death is swallowed up in victory. O death, where is your victory? O death, where is your sting?', reflection:'Easter is not a metaphor. It is a historical fact that has implications too large to fit inside history.', body:`The stone is rolled. The grave is empty. The women are running back to tell the others, afraid and joyful and out of breath.\n\nThis is the day. The whole Christian calendar leans on this day. Every Sunday, every communion, every baptism — they all point here.\n\nIf you are feeling it today, let yourself feel it. The joy, the strange lightness, the sense that the world is not as stuck as it looks.\n\nIf you are not feeling it, that is okay too. The resurrection does not depend on your mood. The stone was rolled. The tomb was empty. He is not here. He is risen.\n\nLet that be enough, for today and for the rest of your life.`, prayer:'Lord, You have done the impossible. I believe. Help my unbelief. Amen.', dur:300, season:'easter' },
  { theme:'gratitude', title:'For Thanksgiving', ref:'Psalm 107:1', text:'Give thanks to the Lord, for he is good, for his steadfast love endures forever.', reflection:'Gratitude is not a holiday. It is a practice. The holiday is just the calendar telling you to pay attention for a day.', body:`The table is set. The people you love are around it, or they are not, and the empty chair has its own weight.\n\nToday is a day to count. Not big things, necessarily. The day you woke up. The friend who called. The fact that the laundry is done. The fact that the laundry is not done, and the world did not end.\n\nThe Lord does not require you to be grateful for everything. He requires you to notice. To pause. To say, "thank you," for at least one thing, before the day swallows you.\n\nOne thing. That is the practice. The rest is grace.`, prayer:'Lord, thank You. For the table, for the people, for the empty chair that still means something, for the breath in my lungs. Amen.', dur:300, season:'ordinary' },
  { theme:'joy', title:'For Christmas Eve', ref:'Luke 2:14', text:'Glory to God in the highest, and on earth peace among those with whom he is pleased.', reflection:'The gospel begins not with a king, but with a baby, in a feed trough, in a barn. God chose the bottom of the pile to enter the world.', body:`The candles are lit. The songs are being sung. The children are asleep on the floor, dreaming of the morning.\n\nTonight, the world tilted. A long time ago, in a place you have never been, a woman gave birth, and the world broke open.\n\nHe was not what anyone expected. He came quietly, to the wrong family, in the wrong town, at the wrong time of year. He came to the bottom. He came to the people no one was looking at.\n\nAnd that is good news, tonight, for you. The God who runs the universe has been, for a long time, on the side of the overlooked. Of the small. Of the tired. Of you.\n\nSleep well. He is near.`, prayer:'Lord, You came. Thank You for coming. Thank You for coming as a baby, so we would not be afraid. Amen.', dur:300, season:'christmas' },

  // ── World & global issues ──
  { theme:'hope', title:'For a World at War', ref:'Micah 4:3', text:'He shall judge between many peoples, and shall arbitrate between strong nations far away; they shall beat their swords into plowshares.', reflection:'The world is broken in ways that politics cannot fix. But the Lord is the Lord of the nations, and He has not abdicated.', body:`You saw the news. The images will not leave you. Children. Families. Cities in the wrong hands. The cruelty of it sits in your chest like a stone.\n\nThe Lord sees the same images. He is not indifferent. The cross is the proof. God Himself entered the worst of what we do to each other, and He did not do so from a throne. He did so from a victim\'s place.\n\nPray. Pray for the leaders, even the ones you cannot stand. Pray for the soldiers on all sides. Pray for the civilians, especially the children, especially the parents, especially the old.\n\nYour prayer is not small. Your prayer joins the prayer of Jesus, who is at this moment interceding for the same people you are interceding for.`, prayer:'Lord of the nations, have mercy. On the children. On the soldiers. On the leaders. On us all. Bring Your peace. Amen.', dur:300, season:'ordinary' },
  { theme:'hope', title:'For the Climate and the Earth', ref:'Genesis 2:15', text:'The Lord God took the man and put him in the garden of Eden to till it and keep it.', reflection:'Creation is not a backdrop. It is not scenery. It is the first gift. To waste it is to wound the hand that gave it.', body:`The fires. The floods. The species we will not see again. The weather that is no longer weather but warning.\n\nYou are not imagining it. The earth is groaning, Paul says, and we are part of the groaning.\n\nThe Lord has given us this place as a stewardship, not a possession. We have been careless. We can be careful, again. The small acts are not nothing — the recycling, the turning off, the choosing, the conversation, the vote.\n\nBut the small acts are not enough alone. We need the grace of God, which makes us into people who can imagine a different way, who can repent, who can begin again.\n\nPray. Then act. Then pray again.`, prayer:'Lord, give us the grace to care for what You have made. Make us faithful stewards. Make us gentle. Amen.', dur:300, season:'ordinary' },
  { theme:'love', title:'For the Refugee', ref:'Leviticus 19:34', text:'The stranger who sojourns with you shall be to you as the native among you, and you shall love him as yourself.', reflection:'The people Jesus loved most were the ones in motion. The refugees, the migrants, the ones who had been turned away.', body:`Somewhere tonight, a family is sleeping in a place they did not plan to sleep. They have left everything. The children do not understand. The parents do, too well.\n\nThe Lord was once a refugee. He slept in Egypt as a baby. He knows the cold of an unfamiliar country, the strange food, the language that does not belong to you.\n\nHe is with them. He is also asking what you will do. The room you have is not just a room. The food in your kitchen is not just food. The vote you cast is not just a vote.\n\nLove your neighbor. He is in the next town, or across the sea. He is the same command.`, prayer:'Lord, for the refugee, for the migrant, for the one in a strange land tonight. Be their home until they find one. Amen.', dur:300, season:'ordinary' },
  { theme:'hope', title:'For the Oppressed', ref:'Isaiah 1:17', text:'Learn to do good; seek justice, correct oppression; bring justice to the fatherless, plead the widow\'s cause.', reflection:'Justice is not optional. It is not a political position. It is part of what it means to be made in the image of God.', body:`Someone is being crushed tonight. By a system, by a person, by a structure that was designed to crush them. They are tired. They are out of voice. They have run out of ways to be heard.\n\nThe Lord is on the side of the crushed. He has always been on the side of the crushed. He hears the cry of the oppressed, the Psalmist says, and He has not stopped hearing it.\n\nYou may not be able to fix the system. You may not even know the system. But you can be a voice. You can refuse to be silent. You can vote, you can give, you can show up, you can listen.\n\nJustice is a long, slow, communal work. The Lord has been at it for a long time. You are invited to join.`, prayer:'Lord, for those who are crushed. Use my voice, my hands, my time, my money, my vote. Use me. Amen.', dur:300, season:'ordinary' },
  { theme:'hope', title:'For Those Who Are Suffering Persecution for Their Faith', ref:'1 Peter 4:16', text:'Yet if anyone suffers as a Christian, let him not be ashamed, but let him glorify God in that name.', reflection:'There are brothers and sisters, tonight, in prison for the name. They are not far away. They are part of the same body.', body:`In some places, to be a Christian is to risk your life. To own a Bible. To pray in a group. To speak the name of Jesus in the wrong room.\n\nYou have never been asked to choose between Jesus and your safety. They have. They are choosing Jesus. Tonight.\n\nThe Lord is with them in a way that you, in your safety, cannot fully understand. He is closer in the prison than in the comfortable room. That is the strange economy of the cross.\n\nPray for them. Send what you can. Speak their names. They are not strangers. They are the family.`, prayer:'Lord, for my brothers and sisters in chains tonight. Be their comfort. Be their courage. Bring them out, in Your time. Amen.', dur:300, season:'ordinary' },
  { theme:'love', title:'For the One Who Has No One', ref:'Psalm 68:6', text:'God settles the solitary in a home; he leads out the prisoners to prosperity.', reflection:'The single most repeated promise in the Bible is "I will be with you." The loneliness is not the end of the story.', body:`You are alone tonight. Maybe not by circumstance. Maybe by choice. Maybe by a long chain of choices that you are not proud of, or a long chain of things that were done to you that you did not deserve.\n\nIt does not matter how you got here. You are here.\n\nThe Lord is here with you. He is closer than the chair you are sitting in. He has always been closer than the loneliness would let you believe.\n\nYou are not too far gone. You are not too old. You are not too broken. He is the God who settles the lonely in a home. He has a place for you. The place is Him.\n\nWait for Him. He is coming. He is already here.`, prayer:'Lord, I am alone. Be with me. Speak to me. Let me feel You. Amen.', dur:300, season:'ordinary' },

  // ── More seasonal & everyday ──
  { theme:'gratitude', title:'For the First Cup of Coffee', ref:'Psalm 104:14', text:'He causes the grass to grow for the cattle, and the grain for the food of man.', reflection:'Ordinary grace is still grace. The cup of coffee is not less holy than the sunrise.', body:`You are here. The kettle has boiled. The mug is in your hand. The day has not started yet. There is still a moment, just a moment, where the day is a blank page.\n\nWhat will you do with it? You do not have to know. You only have to be in this moment, this warm cup, this one breath.\n\nThe Lord is in the morning. He is in the steam. He is in the first sip. He does not require you to do anything grand. He is only asking for the day. You can give it to Him, one cup at a time.\n\nThis is the day. It is yours. Drink it slowly.`, prayer:'Lord, thank You for the morning. Thank You for the cup. Thank You for another day. Walk with me through it. Amen.', dur:240, season:'ordinary' },
  { theme:'stillness', title:'For the In-Between', ref:'Ecclesiastes 3:1', text:'For everything there is a season, and a time for every matter under heaven.', reflection:'In-between is not a failure of pacing. It is a place. Some of the most important work of your life will happen here.', body:`You are between things. Between jobs. Between relationships. Between the old self and the new one. Between the last chapter and the next one.\n\nIt is uncomfortable. In-between is uncomfortable by definition. You cannot go back. You cannot yet go forward. You can only be here.\n\nThe Lord meets people in the in-between. In the wilderness. In the exile. In the long night between the promise and its fulfillment. He is not in a hurry. He is walking with you. He is more interested in who you are becoming than in where you are going.\n\nBe here. Be patient. The next chapter is being written, in you, in silence.`, prayer:'Lord, I am in-between. Teach me what I am meant to learn here. Amen.', dur:300, season:'ordinary' },
  { theme:'gratitude', title:'For the Friend at the Door', ref:'Proverbs 17:17', text:'A friend loves at all times, and a sibling is born for adversity.', reflection:'Friendship is not a luxury. It is a therapy the Lord has prescribed. Use it.', body:`They showed up. The text was "On my way" and the doorbell rang. They brought food. They brought wine. They brought themselves.\n\nYou do not deserve them. None of us do. That is the point of them. Grace in the form of a person, sitting on your couch, asking nothing, offering the only thing that actually helps, which is presence.\n\nThank them. Not with a generic "thanks." With something specific. With something that shows you saw what they did, and what it cost them, and how much it mattered.\n\nThe Lord gives us friends the way He gives us breath — not because we earned it, but because we cannot live without it.`, prayer:'Lord, thank You for this friend. Help me to be a friend like this. Help me to show up. Amen.', dur:240, season:'ordinary' },
  { theme:'courage', title:'For the Parent Sending a Child Off', ref:'Proverbs 22:6', text:'Train up a child in the way he should go; even when he is old he will not depart from it.', reflection:'The hardest thing a parent does is to not be the answer anymore. The letting go is part of the love.', body:`The bags are packed. The room is half-empty. The child you have known for eighteen, twenty-two, twenty-eight years is leaving, and the house is going to be a different shape.\n\nYou have done the work. You have taught what you know. You have shown up for the bedtime and the breakfast and the soccer game and the late-night conversation. They are leaving because you did your job.\n\nIt will not feel like a victory. It will feel like an amputation. Some nights it will feel like both at once.\n\nThe Lord, who let His own Son go to a cross, knows the math of this. He did not love His Son less for letting Him go. He loved Him in the letting go.\n\nLet them go. They will come back. Or they will not. Either way, the love is already finished. It is already complete.`, prayer:'Lord, I am letting go. Hold them for me. And hold me. Amen.', dur:300, season:'ordinary' },
  { theme:'love', title:'For the One Who Has Forgotten How to Be Loved', ref:'1 John 4:19', text:'We love because he first loved us.', reflection:'The most damaging thing is not that you were not loved. It is that you believed it. The lie is the wound, not the absence.', body:`You do not know how to receive. You give, give, give, and when love comes back to you, you do not know what to do with your hands.\n\nThe Lord has been loving you the whole time. Quietly, patiently, without asking you to perform. He has been loving you through the small good things, the door held open, the friend who texted first, the warm day, the song on the radio, the meal that arrived without asking.\n\nYou are not too old. You are not too late. You are not too broken.\n\nYou are loved. You are loved. You are loved.\n\nLet that be the whole of your prayer today.`, prayer:'Lord, teach me to receive. Teach me that I am loved. Amen.', dur:300, season:'ordinary' },
  { theme:'courage', title:'For the Prodigal\'s Parent', ref:'Luke 15:20', text:'While he was still a long way off, his father saw him and was moved with compassion, and ran and embraced him and kissed him.', reflection:'They may not come back. But you can keep the door open. That is the whole of your work, the whole of your hope.', body:`You are waiting. You have been waiting for years, for a call, for a sign, for a turn. The waiting is its own kind of loss, and it is real, and it is allowed to hurt.\n\nYou are not a failure. You did not cause this. You cannot control it. The Lord knows this. The Lord weeps with you. The parable of the lost son is, more often than not, told to the parent who is left behind.\n\nThe father in the story did not go find the son. He waited. He kept the door. He watched the road. He was ready when the son, finally, came over the hill.\n\nYou do not know if your child will come over the hill. But you can be ready. You can keep the door. The Lord is with you in the watching.`, prayer:'Lord, I am waiting. Be patient with me. And bring them home. In Your time. Amen.', dur:300, season:'ordinary' },

  // ── Aging & end of life ──
  { theme:'wisdom', title:'For the Elder', ref:'Psalm 92:14', text:'They still bear fruit in old age; they are ever full of sap and green.', reflection:'Age is not a wind-down. It is a harvest. The thing you have been doing all your life is what you are still doing.', body:`You are not what you were. The knees are not what they were. The mornings are slower. The names of the grandchildren are sometimes late.\n\nThis is not a loss. It is a season. And the season has its own grace.\n\nYou have lived long enough to know what matters, and what does not. To know that the small things were the big things all along. To know that the people you love are the only thing you ever owned.\n\nThe Lord is with you in the slowing. He is with you in the long afternoons. He is with you in the chair by the window. He is pleased with you. He has always been pleased with you.\n\nThe fruit you are bearing now is patient, and quiet, and wise. It is the fruit of having lived.`, prayer:'Lord, thank You for the long life. Thank You for the slowing. Be with me in the afternoons. Amen.', dur:300, season:'ordinary' },
  { theme:'hope', title:'For a Life That Is Winding Down', ref:'2 Timothy 4:7', text:'I have fought the good fight, I have finished the race, I have kept the faith.', reflection:'You have done it. The race is the running, not the winning. You finished. Be at peace.', body:`The end is closer than the beginning. You can feel it, in the way the body moves, in the way the years pile up behind you.\n\nIt is okay to be tired. It is okay to let go. The Lord is not asking you to be what you were. He is asking you to trust Him with the closing.\n\nYou have loved well. You have worked hard. You have shown up. The Lord saw every one of those days, even the ones that felt invisible. He is keeping a record that you will be glad to read, one day, when the reading is possible.\n\nFor now, rest. Rest is not a failure. Rest is a kind of finishing.\n\nThe Lord is with you in the unwinding. He will be with you in the next thing, too.`, prayer:'Lord, I am tired. Take me home, in Your time. And until then, give me peace. Amen.', dur:300, season:'ordinary' },
  { theme:'love', title:'For the One Who Has Lost a Spouse', ref:'1 Thessalonians 4:13', text:'But we do not want you to be uninformed about those who sleep in death, so that you do not grieve like the rest of mankind, who have no hope.', reflection:'The house is the same. The chair is empty. Heaven is not a place you believe; it is a person you will see.', body:`The mornings are the worst. Waking up in a bed that has only one side used. Making coffee for one. The muscle memory of two.\n\nYou do not have to be brave. You do not have to be okay. You have permission to be the person who lost their person, and to take as long as you need.\n\nBut there is a hope, even here. The Lord is the God of the living, not of the dead. They are not gone. They are with Him, in a way you cannot yet see. And one day, when you see them again, the years between will feel like a long breath held.\n\nUntil then, you are not alone. The Lord is with you. So is the one you love, in a way you cannot yet name.`, prayer:'Lord, I miss them. Hold me. And show me, sometimes, that they are not far. Amen.', dur:300, season:'ordinary' },
  { theme:'hope', title:'For Those with No Children', ref:'Psalm 113:9', text:'He gives the barren woman a home, making her the joyous mother of children. Praise the Lord.', reflection:'Your hands are not empty. They have held other things. The Lord is not punishing you. He is shaping you.', body:`The question you cannot stop being asked. The announcement on social media. The baby shower you RSVP\'d no to.\n\nYour arms are not empty. They have held other things. Books, friends, second-graders, your partner, a sick neighbor, a Sunday school class, a thousand small kindnesses that no one will ever put on a card.\n\nThe Lord sees your longing. He honors it. He is not punishing you. He is not withholding. He is shaping you into a person with a particular kind of strength — the strength of those who have learned to hold loosely, to love past the absence, to find the family in the friends, to make a home out of a life that did not look the way they planned.\n\nYou are not less. You are not behind. You are beloved.`, prayer:'Lord, hold my longing. Show me the children I have. Make me a mother in ways I did not plan. Amen.', dur:300, season:'ordinary' },

  // ── More practical everyday ──
  { theme:'focus', title:'For the Morning of an Interview', ref:'Philippians 4:6', text:'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.', reflection:'You have prepared. You have done the work. The rest is in hands bigger than yours.', body:`You will wake up early. You will iron a shirt. You will look in the mirror and not be sure.\n\nYou have done the work. The résumé, the practice questions, the outfit laid out, the route planned. You have done everything a person can do.\n\nThe Lord is doing the rest. He is in the room where you will be interviewed. He is in the voice of the person on the other side of the table. He is in the question that is asked, and the answer that comes out of your mouth, and the look in their eyes when you finish.\n\nYou do not have to perform. You only have to show up, and be who you are. The Lord will take it from there.\n\nBreathe. You have done the work.`, prayer:'Lord, be with me in the room. Speak through me. And let the result be Yours. Amen.', dur:240, season:'ordinary' },
  { theme:'courage', title:'For a Hard Conversation You Have Been Avoiding', ref:'Ephesians 4:15', text:'Rather, speaking the truth in love, we are to grow up in every way into him who is the head, into Christ.', reflection:'The truth told in love is the hardest, bravest, most loving thing a person can do. It is also the rarest.', body:`You have been drafting the conversation in your head for weeks. Rehearsing. Walking away. Coming back. The fear of what will happen if you say it is bigger than the cost of not saying it. But the cost of not saying it is also real. The thing is growing, in the silence.\n\nSay it. Say it kindly. Say it clearly. Do not say it all at once. Do not say it in anger. Do not say it as an attack. Say it as a prayer, almost. As a laying down of what is true, in front of the person you love.\n\nThe Lord is in the truth. He is also in the love. If you can hold both, you can say the thing.\n\nThe conversation is not the end of the relationship. The truth is not the end of the love. It is, often, the beginning.`, prayer:'Lord, give me the words. Give me the courage. Give me the kindness. Be in the room. Amen.', dur:300, season:'ordinary' },
  { theme:'rest', title:'For the Weekend You Have Been Looking Forward To', ref:'Exodus 20:8', text:'Remember the Sabbath day, to keep it holy.', reflection:'Rest is not the absence of work. It is the presence of trust. You are trusting the world to hold itself together for a day.', body:`The week is over. The laptop is closed. The phone is on silent. You are going to do nothing, on purpose, for a couple of days.\n\nThe Lord, who rested on the seventh day, is not going to be disappointed in you. He is the one who invented the rest. He is the one who said, it is good, and stopped.\n\nStop. Sleep late. Read something useless. Walk somewhere green. Eat something good. Be with someone you love, and do not multitask. Be fully there.\n\nYou have earned this, in the sense that you have done the work, but you have also earned it in the deeper sense: you are a human being, and human beings were not designed to go forever.\n\nThe Lord is in the rest. Receive it.`, prayer:'Lord, thank You for the weekend. Help me to actually rest. To be here. To be with the people I love. Amen.', dur:300, season:'ordinary' },
  { theme:'gratitude', title:'For an Ordinary Day', ref:'Psalm 118:24', text:'This is the day that the Lord has made; let us rejoice and be glad in it.', reflection:'The miracle is not the spectacular day. The miracle is the ordinary one. The fact that you are in it, and that it is enough.', body:`Nothing is happening today. There is no crisis. There is no celebration. There is the morning, the lunch, the afternoon, the evening. The traffic, the errands, the long pauses.\n\nThis is the day the Lord has made. Not the great days. Not the terrible ones. This one. The ordinary one. The one that will be over by bedtime and never, ever come back.\n\nNotice it. Notice the cup of tea, the way the light comes in, the friend who calls, the dog who is happy to see you. Notice what is not on fire. Notice what is working. Notice that you are alive, and that this is a day, and that the day is a gift.\n\nThe Lord is in the ordinary. The Lord is in this.`, prayer:'Lord, thank You for this day. For the ordinary. For the in-between. Let me see Your hand in it. Amen.', dur:240, season:'ordinary' },
  { theme:'rest', title:'For a Hard Season of Parenting', ref:'Isaiah 66:13', text:'As one whom his mother comforts, so will I comfort you.', reflection:'You are not the only one who has parented a hard child. The Lord Himself has. The cross was His parenting moment.', body:`The hard year. The year of the door slamming. The year of the lying. The year of the kid you do not recognize. You have been doing this alone, and you are tired in a way that sleep does not fix.\n\nThis is not because you are failing. This is because parenting a hard child is hard. It is one of the hardest things a human being can do. It will not be this way forever.\n\nThe Lord is with you. He is the God of the door-slammers. He was a door-slammer Himself, at twelve, in the temple, worrying His mother half to death.\n\nTake a breath. The kid is still a kid. The love is still the love. The hard year will end. You will come out the other side, scarred, wiser, and with a new respect for every parent in the world.`, prayer:'Lord, hold this child. And hold me. We are both going to make it. By Your grace. Amen.', dur:300, season:'ordinary' },
  { theme:'courage', title:'For a New Venture', ref:'Joshua 1:9', text:'Be strong and courageous. Do not be frightened or dismayed, for the Lord your God is with you wherever you go.', reflection:'The venture will not save you. But it might be the way the Lord saves you through. The venture is the door; the Lord is the destination.', body:`You are starting something. A business. A book. A marriage. A move. A new thing that you have never done before, and that you are not sure you are ready for.\n\nYou are not ready. That is the point. The Lord does not look for ready. He looks for available.\n\nHe will be with you in the middle of it. He will be with you in the failures, and the small wins, and the long, quiet, middle parts where nothing is happening and you wonder if you are doing it wrong.\n\nHe is doing it through you. The work is His. The calling is His. The outcome is His. You are only the hands.\n\nThat is enough. Be the hands.`, prayer:'Lord, I am starting. Hold my hand. Be with me in the middle. Bring it to what You have planned. Amen.', dur:300, season:'ordinary' },
  { theme:'hope', title:'For the Lonely', ref:'Hebrews 13:5', text:'I will never leave you nor forsake you.', reflection:'Loneliness is not the same as aloneness. The Lord was alone on the cross so that you would never have to be.', body:`Tonight, the house is quiet. The phone is not ringing. The friends are busy, or the friends are gone. The longing is sharp, and old, and very tired.\n\nYou are not the only one. There are more lonely people tonight than there are accompanied ones. This is the strange, secret math of the world.\n\nThe Lord is with you. He is with you in the silence, in the way no human can be. He knows your name. He knows the specific shape of your loneliness. He is closer than the next room.\n\nYou may not feel Him tonight. That is okay. Feelings are not the measure. He is there.\n\nTomorrow, reach out to one person. Send one text. Make one call. The loneliness is real, and the cure is real, and it often starts with you.`, prayer:'Lord, I am lonely. Sit with me. And help me to reach out tomorrow. Amen.', dur:300, season:'ordinary' },
  { theme:'gratitude', title:'For the Friend Who Reads With You', ref:'Ecclesiastes 4:9', text:'Two are better than one, because they have a good return for their labor.', reflection:'The book is half the gift. The friend is the other half. Reading together is one of the holiest things two people can do.', body:`You are in a coffee shop with a friend, and you are reading. The same book, separately. Or different books, with the same quiet.\n\nThis is prayer. Or close to it. The quiet attention to a page is its own form of attention to the world, to the soul, to the Lord.\n\nThe friend is not saying much. The friend is not saying anything. The friend is just there, in the chair, in the warm room, in the afternoon. That is enough. That is the whole of the friendship.\n\nThe Lord is in the books. He is in the quiet. He is in the friend. He is in the afternoon. Be here.`, prayer:'Lord, thank You for this friend. For books. For quiet. For coffee. Amen.', dur:240, season:'ordinary' },

  // ── Closing meditation ──
  { theme:'gratitude', title:'For the End of the Day', ref:'Psalm 4:8', text:'In peace I will lie down and sleep, for you alone, O Lord, make me dwell in safety.', reflection:'You do not have to solve the world before sleep. The world will be there in the morning. You, tonight, can rest.', body:`The day is over. The dishes are done, or not. The emails are unanswered, or answered. The work will still be there.\n\nYou will not. You will be here, in this bed, with the pillow, with the dark, with the breath that is finally slowing down.\n\nThe Lord is keeping watch. He does not sleep. He is keeping watch over you, and over the world you cannot keep watch over. He is large enough for the whole thing, and small enough to be with you in this room.\n\nYou did enough. You were enough. The day was enough. Tomorrow is in His hands.\n\nClose your eyes. He is here.`, prayer:'Lord, thank You for the day. Forgive me for the parts I did not do well. Hold me while I sleep. Amen.', dur:240, season:'ordinary' },
];

// ─── 40+ prayers for occasions, conditions, world issues ──────
const prayers = [
  // Daily rhythm
  { title:'On Waking', category:'morning', body:'Lord, I am awake. The day is before me, the coffee in my hand. Be the first thought. Be the breath before the thought. Walk with me through whatever comes. Teach me what I am to learn. Show me the one You have for me to love. I am Yours, before I am mine. Amen.' },
  { title:'On Going to Bed', category:'evening', body:'Lord, the day is done. Whatever I did, I did. Whatever I did not do, I did not. Forgive the one, and accept the other. Hold me while I sleep. Hold the people I love, near and far. Be my guard, and my peace. Amen.' },
  { title:'For the Midday', category:'other', body:'Lord, it is the middle. I have already been up for hours, and the afternoon is long. Renew me. Refresh me. Help me to do the next small thing well. Let me see one person the way You see them. Let me speak one kind word. Let me carry one small weight for someone else. In the middle, be my middle. Amen.' },
  { title:'Before a Meal', category:'gratitude', body:'Lord, thank You for this food. For the hands that grew it, the hands that cooked it, the hands that set the table. Thank You for the company, if there is company. Thank You for the quiet, if there is quiet. We eat, and we live, because You are good. Amen.' },
  { title:'For a Long Commute', category:'other', body:'Lord, the road is long. Be the road. Be the music. Be the patience of the person in front of me. Bring me home safely, and let me arrive as a person who has been with You. Amen.' },
  { title:'On a Sunday Morning', category:'morning', body:'Lord, this is the day You made. I am trying to keep it. Help me to set down the work, set down the phone, set down the small anxieties that I have been carrying all week. Be my rest. Be my worship. Be the bread broken. Amen.' },

  // Conditions
  { title:'For Chronic Pain', category:'other', body:'Lord, I hurt every day. The kind of hurt that does not go away. The kind of hurt that makes the small things hard. Be with me in the hurting. Be the patience I do not have. Be the kindness I cannot always give myself. And on the days when the pain is less, help me to be grateful for the less. Amen.' },
  { title:'For a Diagnosis', category:'other', body:'Lord, the word the doctor said is in my chest. I do not want to say it out loud. I do not know what to do. Be the wisdom I cannot find. Be the peace I cannot make. Hold my hand, and the hands of the people I love, and the hands of the doctors and nurses. Walk with me through this. I do not have to see the path. You do. Amen.' },
  { title:'For a Hospital Room', category:'other', body:'Lord, the room is small. The machines are loud. The food is wrong. The people I love are tired. Be the quiet in the room. Be the kind nurse. Be the doctor who listens. Be the healing, however it comes. Be the peace, in the middle of the not-yet-healed. Amen.' },
  { title:'For a Surgery Tomorrow', category:'other', body:'Lord, tomorrow morning I will be in a room with people in scrubs. I will be under. I will be held. Be with me. Be with the surgeon. Be with the family waiting. Bring me out. Bring me through. And when I wake, let the first face I see be a kind one. Amen.' },
  { title:'For Recovery', category:'rest', body:'Lord, the healing is slow. I want it to be fast. Teach me the slow. Teach me the rest. Teach me to let other people help. Teach me that asking for help is not weakness. Be my recovery, in body, in spirit, in time. Amen.' },
  { title:'For a Loved One in the Hospital', category:'other', body:'Lord, I cannot be there right now. I cannot do the thing the doctors do. But I can pray. I can love from far away. Be with the one who is sick. Be with the doctors and nurses. Be with the family that is sitting in the waiting room. Hold us all, near and far. Bring healing, in Your time. Amen.' },
  { title:'For Anxiety and Panic', category:'anxiety', body:'Lord, my chest is tight. My mind is loud. I do not have the words. Let my breath be the prayer I cannot say. Let Your peace meet me in the noise. I cast the worry on You now. Receive it. Amen.' },
  { title:'For Depression', category:'other', body:'Lord, the days are heavy. The bed is heavy. The light is the wrong kind. I do not want to feel this way. I do not want to be a person who feels this way. Be with me in the heavy. Be the light that comes in. Be the friend who calls. Be the doctor who listens. Be the slow, slow healing. Amen.' },
  { title:'For Insomnia', category:'rest', body:'Lord, the ceiling is the same ceiling it was an hour ago. The mind will not stop. The body will not rest. Be the quiet. Be the slow. Take the worries one by one and lay them at Your feet, because I cannot carry them and I cannot sleep and I cannot let them go. Hold me. Help me to rest. Amen.' },
  { title:'For a Pregnancy', category:'gratitude', body:'Lord, this life is growing. I am full of awe and full of fear. Hold this baby. Hold me. Be the strength I do not have. Be the health I am praying for. Be the love that is making a person. Amen.' },
  { title:'For a Miscarriage', category:'other', body:'Lord, I will not hold this one. I do not have the words. The world is full of the babies other people are having, and I am sitting in the empty. Hold the one I will not meet. Hold me. Be with the person I love. Weep with us. We do not understand. Help us to believe that this is not the end. Amen.' },
  { title:'For Infertility', category:'other', body:'Lord, the months are long. The negative tests are heavy. The friends are announcing. Be with me in the waiting. Be with the one I love. Hold the longing. I do not know why this is hard. I do not have to know. Be with me in the hard. Amen.' },
  { title:'For an Addict in the Family', category:'other', body:'Lord, I cannot save them. I have tried. I have said the right things, the wrong things, the quiet things, the loud things. Be with the one I love. Break the thing that has hold of them. Give them the willingness that I cannot give. And give me the peace to keep loving them, without losing myself. Amen.' },
  { title:'For the One Who Is Suicidal Tonight', category:'other', body:'Lord, it is dark. The thought is loud. I do not want to be here. I do not want to feel this way. Be the reason I do not act. Be the friend who calls. Be the hotline. Be the morning. Be the slow coming back. I am not ready to die. Help me to remember that. Amen.' },
  { title:'For a Caregiver Who Is Burning Out', category:'rest', body:'Lord, I have been doing this for a long time. The days blur. The person I love is so different from the person I married / parented / befriended. I am tired. I am not complaining. I am just tired. Rest me. Send me one small kindness today. Remind me why I started. And let me feel, just for a moment, that I am not doing this alone. Amen.' },

  // World & global
  { title:'For Those in War', category:'other', body:'Lord of the nations, have mercy. On the soldier. On the civilian. On the child. On the mother. On the father. On the one who has been displaced. On the one who has lost everything. Bring peace. Bring an end. Use the leaders, and remove the ones who are not making peace. We pray for peace. We pray for justice. We pray for the day when swords become plowshares. Amen.' },
  { title:'For Refugees and Migrants', category:'other', body:'Lord, tonight a family is sleeping in a place they did not plan to sleep. They have left everything. They are in a strange land. They do not speak the language. They are afraid. Be with them. Be their home. Open doors. Soften hearts. Make the path straight. Use us, in our countries, to welcome the stranger. Amen.' },
  { title:'For Those Who Are Persecuted for Their Faith', category:'other', body:'Lord, there are brothers and sisters in chains tonight, for the name. They are praying the same prayers we are praying. They are reading the same Bible. They are trusting the same Jesus. Be with them in the prison. Be with them in the fear. Be the courage that does not give up. And bring them out, in Your time. Amen.' },
  { title:'For the Earth', category:'other', body:'Lord, the world You made is groaning. The ice is melting. The forests are burning. The animals are going. We have not been good stewards. Forgive us. Make us careful. Make us willing. Make us into people who can imagine a different way. And grant us the years, and the wisdom, to make it happen. Amen.' },
  { title:'For the Oppressed', category:'other', body:'Lord, the world has always crushed the weak. It is doing it now, somewhere, tonight. The system is large. The voice is small. But You are the God who heard the cry of the Israelites. You are the God who parted the sea. Hear the cry. Move the hand. Use us to be part of the answer. Amen.' },
  { title:'For a World Divided', category:'other', body:'Lord, we are afraid of each other. The walls are high. The stories are loud. The other side is the wrong side, we say, on both sides. Break the walls. Soften the stories. Make us into people who can listen, who can doubt ourselves, who can see the image of You in the face of the stranger. Make us one, in the way You are one. Amen.' },
  { title:'For Those Affected by Natural Disasters', category:'other', body:'Lord, the storm came, and the house is gone. The flood came, and the field is gone. The fire came, and the years are gone. Be with the people who are starting over. Be with the people who are coming to help. Give them the resources, the courage, the community. Be the one who does not leave, even when everything else has. Amen.' },
  { title:'For the Hungry', category:'other', body:'Lord, tonight, children are going to bed hungry. Tonight, parents are skipping meals. Tonight, the food is gone, and the money is gone, and the dignity is gone. Be with them. Move the hands of the ones who have. Open the eyes of the ones who do not see. And make us into people who share. Amen.' },
  { title:'For Justice in the Courts', category:'other', body:'Lord, the law is not always just. The judges are not always wise. The prisons are full. The wrong people are free, and the right people are locked up. Be with the wrongly accused. Be with the lawyers who fight for them. Be with the judges who pray before they decide. Make justice roll down, like waters. Amen.' },
  { title:'For Peace Between Nations', category:'other', body:'Lord, history is full of wars, and the weapons are getting worse. The hands on the buttons are still human. Be with the diplomats. Be with the ones who choose the harder path of peace. Make us, the people, into a force that demands peace. Be the peace the world cannot make for itself. Amen.' },

  // Life transitions
  { title:'For a Wedding Day', category:'gratitude', body:'Lord, today they are getting married. They have decided, in front of family and friends, to do this for the rest of their lives. Be with them. Be the patience. Be the kindness. Be the laughter on the hard days. Be the one they turn to, on the days they cannot turn to each other. Bless them, and keep them. Amen.' },
  { title:'For a Funeral', category:'other', body:'Lord, today we bury them. The body is in the ground, or the flame, or the sea. The soul is with You. The grief is with us. Be with the family. Be with the friend. Be with the one who did not get to say the thing. Be the resurrection, in the middle of the death. Hold us, in the church, in the line, in the car, in the bed at night. We will see them again. We will. Amen.' },
  { title:'For the Anniversary of a Death', category:'other', body:'Lord, it has been a year. Or five. Or twenty. The wound is still there, in a different shape. Be with me in the remembering. Be with me in the missing. Be the hope that does not give up, even when I cannot feel it. I will see them again. I will. Amen.' },
  { title:'For a Move to a New City', category:'other', body:'Lord, the boxes are packed. The new city is waiting. I do not know anyone there. The church is a question mark. Be my company in the car. Be the first friend. Be the door that opens. Help me to find the people You have for me. And help me to unpack the loneliness, in Your time. Amen.' },
  { title:'For Retirement', category:'other', body:'Lord, the work is over. The desk is cleared. The mornings are suddenly empty. Be with me in the empty. Be the new thing. Be the friend I have not met. Be the place I am supposed to be. Help me to find, in the slowing, a different kind of busy, a different kind of service, a different kind of joy. Amen.' },
  { title:'For Empty Nest', category:'other', body:'Lord, the house is quiet. The room is empty. The last load of laundry is done. Be with me in the quiet. Be with the one who left. Be with the love that does not stop, even when the car is gone. Make this new season good. Make it whole. Make it yours. Amen.' },
  { title:'For a Graduation', category:'gratitude', body:'Lord, they have finished. The years of school, the years of being made, are done. They are walking into the rest of their life. Be with them. Be their wisdom. Be their kindness. Be the friend they call on the hard days. And thank You for the gift of who they have become. Amen.' },
  { title:'For an Adoption', category:'gratitude', body:'Lord, this child is now mine. Or ours. The years of waiting are over. The paperwork is signed. The heart is full. Bless this child. Bless this family. Hold the first days, the middle days, the hard days. Make us, the parents, wise and patient. Make us, the child, safe and seen. Amen.' },

  // Spiritual
  { title:'For When You Cannot Pray', category:'other', body:'Lord, I have no words. I do not feel You. I do not feel anything. Sit with me anyway. Let my silence be the prayer. Let the Spirit pray the prayer I cannot. Be with me in the not-feeling. The not-feeling is not the absence. You are still here. I am still yours. Amen.' },
  { title:'For When You Feel Far From God', category:'other', body:'Lord, You feel far tonight. I am not sure You are listening. I am not sure You are there. Be there anyway. Be the warmth I do not feel. Be the voice I cannot hear. Walk with me in the distance, until the distance closes. I will keep showing up. Keep showing up for me. Amen.' },
  { title:'For When You Have Failed', category:'other', body:'Lord, I did the thing. I said the thing. I am the thing I did not want to be. The guilt is heavy. The shame is louder. Forgive me. Not in the generic way, but in the specific way. Help me to do the next small thing well. Help me to come back, slowly, to the person You made me to be. Amen.' },
  { title:'For When You Have Been Hurt by the Church', category:'other', body:'Lord, I have been hurt by the people who are supposed to be Yours. The hypocrisy. The judgment. The way they used Your name to do unkind things. Be with me in the hurt. Do not let me walk away from You because of them. You are bigger than the church. You are older than the church. You are still here, in the quiet, waiting. Amen.' },
  { title:'For When You Are Tired of Doing the Right Thing', category:'rest', body:'Lord, I am tired of being the bigger person. I am tired of forgiving, of turning the cheek, of swallowing the anger. Be the patience I have run out of. Be the kindness I cannot manufacture. Be the one who fights for me, because I am too tired to fight for myself. Amen.' },
  { title:'For a Renewed Faith', category:'other', body:'Lord, I want to believe again. The way I used to. The way that was easy, before the doubt. I do not want to perform. I want to be. Renew me. Soften me. Open the door I have been standing outside of. I am not sure I will fit, but I am willing to try. Amen.' },
  { title:'For a Fresh Start', category:'morning', body:'Lord, today is a new day. Whatever I was, yesterday. Whatever I did, yesterday. The mercies are new, this morning. Help me to take one step. One small step. Toward the person You made me to be. The rest is yours. The rest has always been yours. Amen.' },
];

// ─── 12 praise songs ───────────────────────────────────────────
const praise = [
  { title:'The Lord Is My Shepherd (Chant)', subtitle:'A simple chant on Psalm 23', key:'D', tempo:72, meter:'4/4', category:'comfort', scripture_refs:['Psalm 23'], reflection:'Sometimes a song is the only prayer we can pray. Sing it slowly. Let the words do what words do.', lyrics:(
`[Verse 1]\nThe Lord is my shepherd, I shall not want.\nHe makes me lie down in green pastures.\nHe leads me beside still waters,\nHe restores my soul.\n\n[Chorus]\nMy shepherd, my shepherd,\nYou are enough for me.\nMy shepherd, my shepherd,\nYou are enough for me.\n\n[Verse 2]\nYea, though I walk through the valley\nOf the shadow of death,\nI will fear no evil,\nFor You are with me.\n\n[Chorus]\n\n[Verse 3]\nYou prepare a table before me\nIn the presence of my enemies.\nYou anoint my head with oil,\nMy cup overflows.\n\n[Chorus]\n\n[Bridge]\nSurely goodness and mercy\nShall follow me all the days of my life,\nAnd I will dwell in the house of the Lord\nForever.`),
    chords:(
`D                A             Bm\nThe Lord is my shepherd, I shall not want\nG                D              A\nHe makes me lie down in green pastures\nD                A             Bm\nHe leads me beside still waters\nG              D       A       D\nHe restores my soul, restores my soul`) },

  { title:'Be Still, My Soul', subtitle:'A setting of Katharina von Schlegel', key:'G', tempo:60, meter:'3/4', category:'comfort', scripture_refs:['Psalm 46:10','Philippians 4:7'], reflection:'Be still is not a command to do nothing. It is an invitation to be present to what is already here.', lyrics:(
`[Verse 1]\nBe still, my soul — the Lord is on thy side;\nBear patiently the cross of grief or pain;\nLeave to thy God to order and provide;\nIn every change, He faithful will remain.\nBe still, my soul — thy best, thy heavenly Friend,\nThrough thorny ways leads to a joyful end.\n\n[Verse 2]\nBe still, my soul — thy God doth undertake\nTo guide the future as He has the past;\nThy hope, thy confidence let nothing shake;\nAll now mysterious shall be bright at last.\nBe still, my soul — the waves and winds still know\nHis voice who ruled them while He dwelt below.\n\n[Verse 3]\nBe still, my soul — the hour is hastening on\nWhen we shall be forever with the Lord;\nWhen disappointment, grief, and fear are gone,\nSorrow forgot, love\'s purest joys restored.\nBe still, my soul — when change and tears are past,\nAll safe and blessed we shall meet at last.`),
    chords:(
`G        D/F#    Em       C\nBe still, my soul, the Lord is on thy side\nG        D/F#    C       G       D\nBear patiently the cross of grief or pain\nG        D/F#    Em       C\nLeave to thy God to order and provide\nG        D       C       G\nIn every change He faithful will remain`) },

  { title:'Come, Thou Fount of Every Blessing', subtitle:'A folk setting of Robert Robinson', key:'G', tempo:84, meter:'3/4', category:'gratitude', scripture_refs:['1 Samuel 7:12','1 John 1:7'], reflection:'Grace is the only thing that can tune a heart that has wandered. Tune yours today.', lyrics:(
`[Verse 1]\nCome, Thou Fount of every blessing,\nTune my heart to sing Thy grace;\nStreams of mercy, never ceasing,\nCall for songs of loudest praise.\nTeach me some melodious sonnet,\nSung by flaming tongues above;\nPraise the mount — I\'m fixed upon it —\nMount of Thy redeeming love.\n\n[Verse 2]\nHere I raise my Ebenezer,\nHither by Thy help I\'m come;\nAnd I hope, by Thy good pleasure,\nSafely to arrive at home.\nJesus sought me when a stranger,\nWandering from the fold of God;\nHe, to rescue me from danger,\nInterposed His precious blood.\n\n[Chorus]\nO to grace how great a debtor\nDaily I\'m constrained to be!\nLet Thy goodness, like a fetter,\nBind my wandering heart to Thee.\nProne to wander, Lord, I feel it —\nProne to leave the God I love;\nHere\'s my heart, O take and seal it,\nSeal it for Thy courts above.`),
    chords:(
`G               C         G\nCome, Thou Fount of every blessing\nD              C           G\nTune my heart to sing Thy grace\nG               C         G\nStreams of mercy, never ceasing\nD              C      G\nCall for songs of loudest praise`) },

  { title:'It Is Well With My Soul (Abridged)', subtitle:'After Horatio Spafford', key:'Db', tempo:66, meter:'4/4', category:'hope', scripture_refs:['Romans 8:28','2 Corinthians 1:3-4'], reflection:'Spafford wrote this on a ship crossing the Atlantic, after losing his daughters. The peace he had was not the absence of pain. It was the presence of God inside the pain.', lyrics:(
`[Verse 1]\nWhen peace like a river attendeth my way,\nWhen sorrows like sea billows roll —\nWhatever my lot, Thou hast taught me to say,\nIt is well, it is well with my soul.\n\n[Chorus]\nIt is well (it is well)\nWith my soul (with my soul)\nIt is well, it is well with my soul.\n\n[Verse 2]\nThough Satan should buffet, though trials should come,\nLet this blest assurance control:\nThat Christ has regarded my helpless estate,\nAnd has shed His own blood for my soul.\n\n[Chorus]\n\n[Verse 3]\nMy sin — O the bliss of this glorious thought —\nMy sin, not in part but the whole,\nIs nailed to the cross, and I bear it no more;\nPraise the Lord, praise the Lord, O my soul!\n\n[Chorus]\n\n[Verse 4]\nAnd, Lord, haste the day when the faith shall be sight,\nAnd the cloud be rolled back as a scroll;\nThe trump shall resound and the Lord shall descend,\nEven so — it is well with my soul.`),
    chords:(
`Db       Ab       Db\nWhen peace like a river attendeth my way\nGb       Ab       Db\nWhatever my lot, Thou hast taught me to say\nDb       Ab       Db\nIt is well, it is well\nGb       Ab       Db\nIt is well with my soul`) },

  { title:'Great Is Thy Faithfulness', subtitle:'A simple setting of Thomas Chisholm', key:'A', tempo:78, meter:'12/8', category:'gratitude', scripture_refs:['Lamentations 3:22-23'], reflection:'The faithfulness of God is not a feeling. It is a fact. The feeling comes and goes. The fact is the foundation.', lyrics:(
`[Verse 1]\nGreat is Thy faithfulness, O God my Father;\nThere is no shadow of turning with Thee;\nThou changest not, Thy compassions they fail not;\nAs Thou hast been, Thou forever wilt be.\n\n[Chorus]\nGreat is Thy faithfulness! Great is Thy faithfulness!\nMorning by morning new mercies I see;\nAll I have needed Thy hand hath provided;\nGreat is Thy faithfulness, Lord, unto me!\n\n[Verse 2]\nSummer and winter, and springtime and harvest,\nSun, moon, and stars in their courses above\nJoin with all nature in manifold witness\nTo Thy great faithfulness, mercy, and love.\n\n[Chorus]\n\n[Verse 3]\nPardon for sin and a peace that endureth,\nThine own dear presence to cheer and to guide;\nStrength for today and bright hope for tomorrow —\nBlessings all mine, with ten thousand beside!\n\n[Chorus]`),
    chords:(
`A        E        F#m       D\nGreat is Thy faithfulness, O God my Father\nA        E        D         A\nThere is no shadow of turning with Thee
A        E        F#m       D
Thou changest not, Thy compassions they fail not
A        E        D         A
As Thou hast been, Thou forever wilt be`) },

  { title:'How Great Thou Art (Abridged)', subtitle:'After Stuart K. Hine', key:'Bb', tempo:84, meter:'4/4', category:'adoration', scripture_refs:['Psalm 19:1-4','Psalm 8'], reflection:'A small life, looking up at a large sky, in awe. That is prayer too.', lyrics:(
`[Verse 1]\nO Lord my God, when I in awesome wonder\nConsider all the worlds Thy hands have made,\nI see the stars, I hear the rolling thunder,\nThy power throughout the universe displayed.\n\n[Chorus]\nThen sings my soul, my Savior God, to Thee:\nHow great Thou art, how great Thou art!\nThen sings my soul, my Savior God, to Thee:\nHow great Thou art, how great Thou art!\n\n[Verse 2]\nWhen through the woods and forest glades I wander\nAnd hear the birds sing sweetly in the trees,\nWhen I look down from lofty mountain grandeur\nAnd hear the brook and feel the gentle breeze.\n\n[Chorus]\n\n[Verse 3]\nAnd when I think that God, His Son not sparing,\nSent Him to die, I scarce can take it in —\nThat on the cross, my burden gladly bearing,\nHe bled and died to take away my sin.\n\n[Chorus]\n\n[Verse 4]\nWhen Christ shall come with shout of acclamation\nAnd take me home, what joy shall fill my heart!\nThen I shall bow in humble adoration\nAnd there proclaim, my God, how great Thou art!\n\n[Chorus]`),
    chords:(
`Bb        F        Gm       Eb\nO Lord my God, when I in awesome wonder\nBb        F        Eb       Bb\nConsider all the worlds Thy hands have made
Bb        F        Gm       Eb
I see the stars, I hear the rolling thunder
Bb        F        Eb       Bb
Thy power throughout the universe displayed`) },

  { title:'What a Friend We Have in Jesus', subtitle:'After Joseph M. Scriven', key:'F', tempo:80, meter:'4/4', category:'comfort', scripture_refs:['John 15:15','Hebrews 4:15-16'], reflection:'The friend who has been through what you have been through is the friend worth telling. Jesus is that friend.', lyrics:(
`[Verse 1]\nWhat a friend we have in Jesus,\nAll our sins and griefs to bear!\nWhat a privilege to carry\nEverything to God in prayer!\nO what peace we often forfeit,\nO what needless pain we bear,\nAll because we do not carry\nEverything to God in prayer!\n\n[Verse 2]\nHave we trials and temptations?\nIs there trouble anywhere?\nWe should never be discouraged —\nTake it to the Lord in prayer.\nCan we find a friend so faithful\nWho will all our sorrows share?\nJesus knows our every weakness —\nTake it to the Lord in prayer.\n\n[Verse 3]\nAre we weak and heavy laden,\nCumbered with a load of care?\nPrecious Savior, still our refuge —\nTake it to the Lord in prayer.\nDo thy friends despise, forsake thee?\nTake it to the Lord in prayer.\nIn His arms He\'ll take and shield thee,\nThou wilt find a solace there.`),
    chords:(
`F        C        F\nWhat a friend we have in Jesus\nBb       C        F
All our sins and griefs to bear
F        C        F
What a privilege to carry
Bb       C        F
Everything to God in prayer`) },

  { title:'Amazing Grace (Common Meter)', subtitle:'After John Newton', key:'G', tempo:72, meter:'3/4', category:'gratitude', scripture_refs:['Ephesians 2:8-9','Titus 2:11'], reflection:'Grace does not ask us to be good first. Grace meets us in the middle of the mess.', lyrics:(
`[Verse 1]\nAmazing grace! How sweet the sound\nThat saved a wretch like me!\nI once was lost, but now am found,\nWas blind, but now I see.\n\n[Verse 2]\n\'Twas grace that taught my heart to fear,\nAnd grace my fears relieved;\nHow precious did that grace appear\nThe hour I first believed.\n\n[Verse 3]\nThrough many dangers, toils, and snares,\nI have already come;\n\'Tis grace hath brought me safe thus far,\nAnd grace will lead me home.\n\n[Verse 4]\nWhen we\'ve been there ten thousand years,\nBright shining as the sun,\nWe\'ve no less days to sing God\'s praise\nThan when we\'d first begun.`),
    chords:(
`G              C         G
Amazing grace, how sweet the sound
D              C         G
That saved a wretch like me
G              C         G
I once was lost but now am found
D              C         G
Was blind but now I see`) },

  { title:'Good, Good Father', subtitle:'A simple praise song for the family table', key:'C', tempo:96, meter:'4/4', category:'adoration', scripture_refs:['Matthew 7:9-11','James 1:17'], reflection:'The kind of father who gives good gifts, not because you have earned them, but because he loves you.', lyrics:(
`[Verse 1]\nYou\'re a good, good Father\nIt\'s who You are, it\'s who You are, it\'s who You are\nAnd I\'m loved by You\nIt\'s who I am, it\'s who I am, it\'s who I am\n\n[Chorus]\nOh, it\'s love so undeniable\nI, I can hardly speak\nPeace so unexplainable\nI, I can hardly think\n\n[Verse 2]\nYou\'re a good, good Father\nIt\'s who You are, it\'s who You are, it\'s who You are\nAnd I\'m loved by You\nIt\'s who I am, it\'s who I am, it\'s who I am\n\n[Bridge]\nAll my life You have been faithful\nAll my life You have been so, so kind\nAll my life You have been faithful\nAll my life You have been so, so kind\n\n[Chorus]`),
    chords:(
`C        G        Am       F
You\'re a good, good Father
C        G        F
It\'s who You are
C        G        Am       F
And I\'m loved by You
C        G        F
It\'s who I am`) },

  { title:'Tremble (Abridged)', subtitle:'A modern declaration of truth', key:'A', tempo:76, meter:'6/8', category:'hope', scripture_refs:['Romans 8:15','2 Timothy 1:7'], reflection:'The Spirit inside you is not a Spirit of fear. The fear is the lie. The Spirit is the truth.', lyrics:(
`[Verse 1]\nIn the name of the Father, in the name of the Son,\nIn the name of the Spirit, Lord, we come.\nWe are gathered together to lift up Your name,\nTo call on our Father, to fall on His grace.\n\n[Pre-Chorus]\nI still believe You\'re the same,\nI still believe You reign,\nPowerful, mighty, unchanging,\nWonder-working, never-failing God.\n\n[Chorus]\nYou are faithful, You are faithful,\nEvery promise You have made,\nYou are faithful, You are faithful,\nLet the redeemed say, "Amen."\n\n[Verse 2]\nIn the name of the Father, in the name of the Son,\nIn the name of the Spirit, Lord, we come.\nWe are gathered together to lift up Your name,\nTo call on our Father, to fall on His grace.\n\n[Pre-Chorus]\n\n[Chorus]\n\n[Bridge]\nThe name above all names\nIs the name of Jesus\nThe name above all names\nIs the name of Jesus`),
    chords:(
`A        E        F#m       D
In the name of the Father, in the name of the Son
A        E        D         A
In the name of the Spirit, Lord we come`) },

  { title:'A Simple Communion Hymn', subtitle:'For the breaking of the bread', key:'D', tempo:64, meter:'4/4', category:'celebration', scripture_refs:['1 Corinthians 11:23-26','Luke 22:19'], reflection:'Take, eat. This is the whole of the gospel, in two hands.', lyrics:(
`[Verse 1]\nBread of the world, in mercy broken,\nWine of the soul, in mercy shed;\nBy whom the words of life were spoken,\nAnd in whose death our sins are dead.\n\n[Verse 2]\nLook on the heart by sorrow broken,\nLook on the tears by sinners shed,\nAnd be Thy feast to us the token\nThat by Thy grace our souls are fed.\n\n[Chorus]\nTake, eat, this is My body.\nTake, drink, this is My blood.\nDo this in remembrance of Me,\nUntil I come again.\n\n[Verse 3]\nLord, in the breaking, You are with us.\nLord, in the pouring, You are near.\nIn every fragment, every silence,\nYour love, Your grace, Your presence, here.`),
    chords:(
`D        A        Bm       G
Bread of the world, in mercy broken
D        A        G         D
Wine of the soul, in mercy shed
D        A        Bm       G
By whom the words of life were spoken
D        A        G         D
And in whose death our sins are dead`) },

  { title:'A Song of Lament (For When There Are No Words)', subtitle:'A short song for grief and protest', key:'Em', tempo:54, meter:'3/4', category:'lament', scripture_refs:['Psalm 13','Psalm 88','Lamentations 3'], reflection:'Lament is a form of worship. The psalms are full of it. The Lord is not afraid of your anger. Bring it to Him.', lyrics:(
`[Verse 1]\nHow long, O Lord? How long?\nWill You forget me forever?\nHow long must I take counsel\nIn my soul, and have sorrow all the day?\n\n[Chorus]\nHear my cry, O God;\nGive heed to my prayer.\nFrom the ends of the earth I call to You,\nWhen my heart is faint.\n\n[Verse 2]\nWhy, O Lord, do You cast off my soul?\nWhy do You hide Your face from me?\nI am afflicted and in pain;\nLet Your steadfast love be my comfort.\n\n[Chorus]\n\n[Verse 3]\nThe Lord is my portion, says my soul,\nTherefore I will hope in Him.\nThe Lord is good to those who wait for Him,\nTo the soul that seeks Him.\n\n[Chorus]`),
    chords:(
`Em       C        G        D
How long, O Lord, how long
Em       C        G        D
Will You forget me forever
Em       C        G        D
How long must I take counsel
Em       C        G        D
In my soul and have sorrow all the day`) },
];

// ─── write all ────────────────────────────────────────────────
let medCount = 31; // start day 31
for (let i = 0; i < meditations.length; i++) {
  const m = meditations[i];
  const dayOfYear = medCount++;
  const name = m.title;
  const obj = {
    day_of_year: dayOfYear,
    title: m.title,
    theme: m.theme,
    season: m.season || 'ordinary',
    scripture_ref: m.ref,
    translation: 'NRSV',
    scripture_text: m.text,
    reflection: m.reflection,
    body: m.body,
    prayer: m.prayer,
    duration_seconds: m.dur || 300,
    launch_batch: 'B2',
    slug: slug(m.title),
    sort_order: dayOfYear,
    is_published: true,
  };
  const file = `${String(dayOfYear).padStart(3,'0')}-${slug(m.title)}.json`;
  await writeJson(MEDITATIONS_DIR, file, obj);
}

let prayerCount = 21;
for (let i = 0; i < prayers.length; i++) {
  const p = prayers[i];
  const obj = {
    title: p.title,
    slug: slug(p.title),
    body: p.body,
    category: p.category,
    sort_order: prayerCount++,
    is_published: true,
  };
  const file = `${slug(p.title)}.json`;
  await writeJson(PRAYERS_DIR, file, obj);
}

let praiseCount = 1;
for (let i = 0; i < praise.length; i++) {
  const s = praise[i];
  const obj = {
    title: s.title,
    slug: slug(s.title),
    subtitle: s.subtitle,
    lyrics: s.lyrics,
    chords: s.chords,
    scripture_refs: s.scripture_refs,
    reflection: s.reflection,
    category: s.category,
    key_signature: s.key,
    tempo_bpm: s.tempo,
    meter: s.meter,
    day_of_year: praiseCount,
    sort_order: praiseCount,
    is_published: true,
  };
  const file = `${String(praiseCount).padStart(2,'0')}-${slug(s.title)}.json`;
  await writeJson(PRAISE_DIR, file, obj);
  praiseCount++;
}

console.log(`✓ Wrote ${meditations.length} new meditations (days 31-${medCount-1})`);
console.log(`✓ Wrote ${prayers.length} new prayers`);
console.log(`✓ Wrote ${praise.length} new praise songs`);
console.log('Done.');
